name: DP-GUIShop
version: 2.2.0
main: com.darksoldier1404.dpgs.GUIShop
authors: [ DEAD_POOLIO_ ]
api-version: 1.20
depend:
  - DPP-Core
softdepend:
  - PlaceholderAPI
commands:
  shop:
    aliases: [ dpgs, 상점, dshop, dpshop ]